health checks for admin and server

diff --git a/.github/workflows/admin-ci.yml b/.github/workflows/admin-ci.yml
--- a/.github/workflows/admin-ci.yml
+++ b/.github/workflows/admin-ci.yml
@@ -76,6 +76,27 @@ jobs:
         run: |
           rm -rf /tmp/.buildx-cache
           mv /tmp/.buildx-cache-new /tmp/.buildx-cache 
+      - name: Health Check
+        run: |
+          docker compose up -d
+          set -e
+          echo "Checking health of admin..."
+          # Retry the health check up to 10 times with a 10-second interval
+          for i in {1..10}; do
+            if docker compose exec admin curl --fail http://localhost:4200/; then
+              echo "Health check passed!"
+              break
+            else
+              echo "Health check failed, retrying in 5 seconds..."
+              sleep 10
+            fi
+          done
+          
+          # If we exhausted all retries and curl still fails, exit the job
+          if ! docker compose exec admin curl --fail http://localhost:4200/; then
+            echo "Health check failed after 10 attempts. Exiting."
+            exit 1
+          fi
     
   lint-admin:
     needs: build-admin
@@ -101,3 +122,27 @@ jobs:
           docker pull ${{ env.ADMIN_IMAGE }}
           docker compose run admin npm run lint
         continue-on-error: true
+  
+  test-admin:
+    needs: build-admin
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Setup Docker Environment
+        run: docker info
+
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Test Admin
+        run: |
+          docker pull ${{ env.ADMIN_IMAGE }}
+          docker compose run admin npm run test
diff --git a/.github/workflows/server-ci.yml b/.github/workflows/server-ci.yml
--- a/.github/workflows/server-ci.yml
+++ b/.github/workflows/server-ci.yml
@@ -86,36 +86,20 @@ jobs:
           docker compose up -d
           set -e
           echo "Checking health of the server..."
-      
           # Retry the health check up to 10 times with a 10-second interval
           for i in {1..10}; do
-            echo "Attempt $i: Checking if the server is up and running..."
-      
-            # Log docker ps output to check container status
-            echo "Running docker ps to check container status:"
-            docker ps -a
-      
-            # If the server container is not running, capture its logs
-            SERVER_STATUS=$(docker inspect -f '{{.State.Status}}' server-server-1)
-            if [ "$SERVER_STATUS" != "running" ]; then
-              echo "Server container is not running. Fetching logs..."
-              docker logs server-server-1
-            fi
-      
-            # Health check endpoint
-            echo "Checking server health endpoint..."
             if docker compose exec server curl --fail http://localhost:3333/health; then
-              echo "Health check succeeded!"
+              echo "Health check passed!"
               break
             else
-              echo "Health check failed. Waiting for 10 seconds before retrying..."
+              echo "Health check failed, retrying in 5 seconds..."
               sleep 10
             fi
           done
-      
-          # After the loop, check if the health check passed
-          if [ $i -eq 10 ]; then
-            echo "Health check failed after 10 attempts."
+          
+          # If we exhausted all retries and curl still fails, exit the job
+          if ! docker compose exec server curl --fail http://localhost:3333/health; then
+            echo "Health check failed after 10 attempts. Exiting."
             exit 1
           fi
   
