add healthcheck.js for admin Dockerfile. Add looping check to container healths in actions for admin and server pipelines

diff --git a/.github/workflows/admin-ci.yml b/.github/workflows/admin-ci.yml
--- a/.github/workflows/admin-ci.yml
+++ b/.github/workflows/admin-ci.yml
@@ -87,32 +87,44 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
-      - name: Confirm containers are up
+      - name: Start Containers
+        run: docker compose up -d
+  
+      - name: Verify Container Health
         run: |
-          docker compose up -d
           set -e
-          echo "Checking health of admin..."
-          # Retry the health check up to 10 times with a 10-second interval
-          for i in {1..10}; do
-            if docker compose exec admin curl --fail http://localhost:4200/; then
-              echo "Health check passed!"
-              break
-            else
-              echo "Health check failed, retrying in 5 seconds..."
-              sleep 10
+          echo "Waiting for containers to become healthy..."
+
+          timeout=60
+          while [ $timeout -gt 0 ]; do
+            unhealthy_found=false
+
+            for service in $(docker compose ps --services); do
+              container_name=$(docker compose ps -q $service)
+              health_status=$(docker inspect --format='{{.State.Health.Status}}' "$container_name")
+
+              if [ "$health_status" != "healthy" ]; then
+                unhealthy_found=true
+                echo "Service $service is not healthy yet."
+              fi
+            done
+
+            if [ "$unhealthy_found" = false ]; then
+              echo "All containers are healthy."
+              exit 0
             fi
+
+            echo "Waiting for services to become healthy..."
+            sleep 5
+            timeout=$((timeout - 5))
           done
 
-          # If we exhausted all retries and curl still fails, exit the job
-          if ! docker compose exec admin curl --fail http://localhost:4200/; then
-            echo "Health check failed after 10 attempts. Exiting."
-            docker compose logs server
-            exit 1
-          fi
+          echo "Error: Not all services became healthy in time."
+          exit 1
 
-      - name: Lint Server
+      - name: Lint Admin
         run: |
-          docker compose run admin npm run lint
+          docker compose exec admin npm run lint
 
       # TODO: Temporarily commenting this out until ARCWELL-387 "Implement Admin unit testing is completed"
 #      - name: Test Server
diff --git a/.github/workflows/server-ci.yml b/.github/workflows/server-ci.yml
--- a/.github/workflows/server-ci.yml
+++ b/.github/workflows/server-ci.yml
@@ -87,28 +87,40 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
-      - name: Confirm containers are up
+      - name: Start Containers
+        run: docker compose up -d
+    
+      - name: Verify Container Health
         run: |
-          docker compose up -d db server
           set -e
-          echo "Checking health of the server..."
-          # Retry the health check up to 10 times with a 10-second interval
-          for i in {1..5}; do
-            if docker compose exec server curl --fail http://localhost:3333/health; then
-              echo "Health check passed!"
-              break
-            else
-              echo "Health check failed, retrying in 5 seconds..."
-              sleep 5
+          echo "Waiting for containers to become healthy..."
+
+          timeout=60
+          while [ $timeout -gt 0 ]; do
+            unhealthy_found=false
+
+            for service in $(docker compose ps --services); do
+              container_name=$(docker compose ps -q $service)
+              health_status=$(docker inspect --format='{{.State.Health.Status}}' "$container_name")
+
+              if [ "$health_status" != "healthy" ]; then
+                unhealthy_found=true
+                echo "Service $service is not healthy yet."
+              fi
+            done
+
+            if [ "$unhealthy_found" = false ]; then
+              echo "All containers are healthy."
+              exit 0
             fi
+
+            echo "Waiting for services to become healthy..."
+            sleep 5
+            timeout=$((timeout - 5))
           done
-          
-          # If we exhausted all retries and curl still fails, exit the job
-          if ! docker compose exec server curl --fail http://localhost:3333/health; then
-            echo "Health check failed after 10 attempts. Exiting."
-            docker compose logs server
-            exit 1
-          fi
+
+          echo "Error: Not all services became healthy in time."
+          exit 1
 
       - name: Lint Server
         run: |
