ARCWELL-459 - Optimize Docker health check for Admin CI (#232)
* add healthcheck.js for admin Dockerfile. Add looping check to container healths in actions for admin and server pipelines

* extend timeout for health check

* revert comment lines to appropriate places

* refactor to singular docker call for health check on services

* add a start period arg onto healthcheck of dockerfile commands

* refactor actions healthcheck to check after intial try, then wait 60 seconds and try once more

diff --git a/.github/workflows/admin-ci.yml b/.github/workflows/admin-ci.yml
--- a/.github/workflows/admin-ci.yml
+++ b/.github/workflows/admin-ci.yml
@@ -87,32 +87,35 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
-      - name: Confirm containers are up
+      - name: Start Containers
+        run: docker compose up -d
+  
+      - name: Verify Container Health
         run: |
-          docker compose up -d
           set -e
-          echo "Checking health of admin..."
-          # Retry the health check up to 10 times with a 10-second interval
-          for i in {1..10}; do
-            if docker compose exec admin curl --fail http://localhost:4200/; then
-              echo "Health check passed!"
-              break
-            else
-              echo "Health check failed, retrying in 5 seconds..."
-              sleep 10
-            fi
-          done
+          echo "Waiting for containers to become healthy..."
 
-          # If we exhausted all retries and curl still fails, exit the job
-          if ! docker compose exec admin curl --fail http://localhost:4200/; then
-            echo "Health check failed after 10 attempts. Exiting."
-            docker compose logs server
-            exit 1
+          # Wait for initial healthcheck to run
+          sleep 15
+
+          # Perform the first health check
+          if docker compose ps -q | xargs docker inspect --format='{{.State.Health.Status}}' | grep -q 'unhealthy'; then
+            echo "Some services are still unhealthy. Retrying after 60 seconds..."
+            sleep 60
+
+            # Perform the second health check
+            if docker compose ps -q | xargs docker inspect --format='{{.State.Health.Status}}' | grep -q 'unhealthy'; then
+              echo "Error: Not all services became healthy in time."
+              exit 1
+            fi
           fi
 
-      - name: Lint Server
+          echo "All services are healthy."
+          exit 0
+
+      - name: Lint Admin
         run: |
-          docker compose run admin npm run lint
+          docker compose exec admin npm run lint
 
       # TODO: Temporarily commenting this out until ARCWELL-387 "Implement Admin unit testing is completed"
 #      - name: Test Server
diff --git a/.github/workflows/server-ci.yml b/.github/workflows/server-ci.yml
--- a/.github/workflows/server-ci.yml
+++ b/.github/workflows/server-ci.yml
@@ -87,28 +87,31 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
-      - name: Confirm containers are up
+      - name: Start Containers
+        run: docker compose up server -d
+    
+      - name: Verify Container Health
         run: |
-          docker compose up -d db server
           set -e
-          echo "Checking health of the server..."
-          # Retry the health check up to 10 times with a 10-second interval
-          for i in {1..5}; do
-            if docker compose exec server curl --fail http://localhost:3333/health; then
-              echo "Health check passed!"
-              break
-            else
-              echo "Health check failed, retrying in 5 seconds..."
-              sleep 5
+          echo "Waiting for containers to become healthy..."
+
+          # Wait for initial healthcheck to run
+          sleep 15
+
+          # Perform the first health check
+          if docker compose ps -q | xargs docker inspect --format='{{.State.Health.Status}}' | grep -q 'unhealthy'; then
+            echo "Some services are still unhealthy. Retrying after 60 seconds..."
+            sleep 60
+
+            # Perform the second health check
+            if docker compose ps -q | xargs docker inspect --format='{{.State.Health.Status}}' | grep -q 'unhealthy'; then
+              echo "Error: Not all services became healthy in time."
+              exit 1
             fi
-          done
-          
-          # If we exhausted all retries and curl still fails, exit the job
-          if ! docker compose exec server curl --fail http://localhost:3333/health; then
-            echo "Health check failed after 10 attempts. Exiting."
-            docker compose logs server
-            exit 1
           fi
+
+          echo "All services are healthy."
+          exit 0
 
       - name: Lint Server
         run: |
