health check server

diff --git a/.github/workflows/server-ci.yml b/.github/workflows/server-ci.yml
--- a/.github/workflows/server-ci.yml
+++ b/.github/workflows/server-ci.yml
@@ -81,6 +81,28 @@ jobs:
           rm -rf /tmp/.buildx-cache
           mv /tmp/.buildx-cache-new /tmp/.buildx-cache
   
+          - name: Health Check
+          run: |
+            docker compose up -d
+            set -e
+            echo "Checking health of the server..."
+            # Retry the health check up to 10 times with a 10-second interval
+            for i in {1..10}; do
+              if docker compose exec server curl --fail http://localhost:3333/health; then
+                echo "Health check passed!"
+                break
+              else
+                echo "Health check failed, retrying in 5 seconds..."
+                sleep 5
+              fi
+            done
+            
+            # If we exhausted all retries and curl still fails, exit the job
+            if ! docker compose exec server curl --fail http://localhost:3333/health; then
+              echo "Health check failed after 10 attempts. Exiting."
+              exit 1
+            fi
+  
   lint-server:
     needs: build-server
 
